---
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Name: mysite
After: 'framework/*','cms/*'
---
SSViewer:
  theme_enabled: false
  # theme: 'simple'
MySQLDatabase:
  connection_charset: 'utf8'
GDBackend:
  default_quality: 75
SiteTree:
  nested_urls: true
  # Disable creating of default pages (like home) on /dev/build
  # create_default_pages: false
Email:
  admin_email: 'info@silverstripe-europe.org'
SiteConfig:
  extensions:
    - 'mysiteSiteConfigExtension'
LeftAndMain:
  extensions:
    - 'mysiteLeftAndMainExtension'
Image:
  extensions:
    - 'ImageExtension'
---
Only:
  environment: 'dev'
---
SSViewer:
  source_file_comments: true
DataObjectAnnotator:
    enabled:
      true
    enabled_modules:
      - mysite
